### ISSUE TITLE
Breaks after upgrading to PureScript 0.15

### ISSUE THREAD

**Issue by dnikolovv** [MaybeJustJames/zephyr#81]
Hey there. After updating to PureScript 0.15 `zephyr` fails with

```
$ zephyr -f Main.main
Error: Failed parsing:
  output/Control.Comonad.Traced/corefn.json
        output/Control.Monad.State/corefn.json
        output/Control.Monad.Error.Class/corefn.json
        output/Control.Monad.Identity.Trans/corefn.json
        output/Main/corefn.json
        ... (346 more)
error Command failed with exit code 1.
```

This is the offending branch https://github.com/dnikolovv/purescriptify/tree/purescript-0.15. You can run `yarn run bundle` to reproduce.

**Comment by MaybeJustJames** [comment]
Have you tried with https://github.com/MaybeJustJames/zephyr/releases/tag/v0.5.2? It looks like the install script you're using pulls in `0.3.2` which is for Purescript `0.13`

**Comment by dnikolovv** [comment]
Oh man.. I didn't even read the `install.js` script, just replaced the binary with `v0.5.2` assuming that it would be used.

Yeah, it works great with `v0.5.2`, sorry!

**Comment by MaybeJustJames** [comment]
No problem :)
